import streamlit as st
import app
import test

def main():
    st.sidebar.title("Navigation")

    # Add 'Home' to the app choices
    choice = st.sidebar.radio("Choose the App", ["Home", "MR Liver Elastography", "Glenoid Track Assessment"])

    if choice == "Home":
        st.title("Welcome to RADCalc!")
        st.write("""
        This application provides two primary functionalities:
        1. **MR Liver Elastography:** Description or brief instruction about this functionality.
        2. **Glenoid Track Assessment:** Description or brief instruction about this functionality.
        
        Please select an option from the sidebar to proceed.
        """)

        # Adding a disclaimer
        st.subheader("Disclaimer")
        st.write("""
        RADCalc is intended for educational and informational purposes only. The results and outputs generated by this app should not be used as a substitute for professional medical advice, diagnosis, or treatment. Always consult with a qualified healthcare provider regarding any medical condition or treatment recommendations. The developers and maintainers of this application accept no responsibility for any consequences resulting directly or indirectly from the use of this application.
        """)
    
    elif choice == "MR Liver Elastography":
        app.run()
    
    elif choice == "Glenoid Track Assessment":
        test.run()

if __name__ == "__main__":
    main()
